services:
  remnanode:
    image: ${CUSTOM_NODE_IMAGE:-ghcr.io/fourgetu/remnawave-node:custom-v0.2.1}
    container_name: remnanode-custom
    hostname: remnanode
    network_mode: host
    restart: always
    cap_add:
      - NET_ADMIN
    ulimits:
      nofile:
        soft: 1048576
        hard: 1048576
    env_file:
      - .env.node
    environment:
      NODE_PORT: ${NODE_PORT:-2222}
      PORT_HOPPING_INGRESS: ${PORT_HOPPING_INGRESS:-nftables}
